### DISCUSSION TITLE
Help in params.yaml charmed magma

### DISCUSSION THREAD

**Discussion by venkatmanavarthi** [magma/magma#15426] [Q&A]
```yaml
vld: 
  - name: mgmtnet                                # Id of the virtual-link-desc where the SGI interface is
    vim-network-name: osm-ext                    # Name of the network in the VIM (The network must exists)
    vnfd-connection-point-ref: 
      - member-vnf-index-ref: "vnf1"             # constituent-base-element-id (In the NSD)
        vnfd-connection-point-ref: vnf-mgmt-ext  # constituent-cpd-id (In the NSD)
        ip-address: "172.21.248.153"             # IP address that will be used in the mgmt interface in the VM
additionalParamsForVnf: 
  - member-vnf-index: "vnf1"                     # constituent-base-element-id (In the NSD)
    additionalParams: 
      - sgi_ipv4_address: "172.21.248.153/22"    # IP address and subnet that will be used in the mgmt interface in the VM, the format x.x.x.x/yy
        sgi_interface: ens3                      # Name of the SGI interface in the VM
        sgi_ipv4_gateway: "172.21.248.1"         # GW of the network used for SGI
        s1_interface: ens4                       # Name of the S1 interface in the VM
```

how to configure this ip addresses, please suggest with an example
