### ISSUE TITLE
Slack notification on failure of bazel LTE integ test workflow should work

### ISSUE THREAD

**Issue by LKreutzer** [magma/magma#13393]
Currently failure of the workflow does not lead to a slack notification. The following error is thrown:

![Screenshot from 2022-07-22 15-33-45](https://user-images.githubusercontent.com/34488763/180450127-5ff5ef16-c48c-4da3-abe9-9788a87a19c6.png)

The Make LTE integ test workflow instead uses the action:
```
     - name: Notify failure to slack
        if: failure() && github.event.workflow_run.event == 'push'
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: "LTE integ test"
          SLACK_AVATAR: ":boom:"
        uses: Ilshidur/action-slack@689ad44a9c9092315abd286d0e3a9a74d31ab78a # pin@2.1.0
        with:
          args: "LTE integration test test failed on [${{ env.SHA }}](${{github.event.repository.owner.html_url}}/magma/commit/${{ env.SHA }}): ${{ steps.commit.outputs.title}}"
```
