### ISSUE TITLE
Investigate and reconfigure integ test workflow triggers

### ISSUE THREAD

**Issue by LKreutzer** [magma/magma#13907]
The workflows:
![Screenshot from 2022-09-13 11-53-24](https://user-images.githubusercontent.com/34488763/189871407-c3e24a87-b6ed-4daa-8c9e-f3042ac2a8e2.png)
(once https://github.com/magma/magma/pull/13865 is merged this also applied to the sudo test workflow)

all have a workflow trigger like
```
on:
  workflow_run:
    workflows:
      - build-all
    branches:
      - master
    types:
      - completed
```

Is this justified in all cases? If not remove this trigger and add a push trigger for the master branch instead.

Requirements:
* if a workflows does not need the build-all WF to run first, then remove the trigger
* BUT still make sure that the WF is then run on master merges
