### ISSUE TITLE
Replace `set-output` in bazel.yml with Environment Files

### ISSUE THREAD

**Issue by LKreutzer** [magma/magma#14310]
```
Run when bazel successful
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```
* here only for bazel.yml
* create follow-up to do this in all affected workflows (with this change as a blueprint)

**Comment by LKreutzer** [comment]
```
      - name: Extract commit title
        # yamllint enable
        if: failure() && github.event_name == 'push'
        id: commit
        run: |
          str="$(jq '.head_commit.message' $GITHUB_EVENT_PATH)"    # get the head_commit message
          echo ::set-output name=title::${str%%\\n*} | tr -d '"'
```
is used frequently in other workflows.

**Comment by LKreutzer** [comment]
Same for 
```
      - name: Tag and push to Jfrog Registry
        id: publish_artifacts
        if: github.event_name == 'push'
        env:
          DOCKER_REGISTRY: "feg-test.artifactory.magmacore.org"
          DOCKER_USERNAME: "${{ secrets.JFROG_USERNAME }}"
          DOCKER_PASSWORD: "${{ secrets.JFROG_PASSWORD }}"
        run: |
          ./ci-scripts/tag-push-docker.sh --images 'gateway_go|gateway_python' --tag "${TAG}" --tag-latest true --project feg
          ARTIFACTS="{\"packages\":[\"$DOCKER_REGISTRY/gateway_go:${TAG}\", \"$DOCKER_REGISTRY/gateway_python:${TAG}\"],\"valid\":true}"
          echo "::set-output name=artifacts::$(echo $ARTIFACTS)"
```
