### ISSUE TITLE
[orc8r] Modify API for subscribers to specify active APNs and APN-specific policies

### ISSUE THREAD

**Issue by andreilee** [magma/magma#2254]
Check the proposal document for accompanying details

```
subscriber:
  id: string
  name: string
  ...
  active_base_names: array[base_name]
  # Policy IDs listed in active_policies define which policies will be installed
  # for every APN of the subscriber
  active_policies: array[string]
  # Keyed by APN IDs, and values list out the policy IDs
  # Keys present define the APNs that the subscriber has access to
  # policy IDs define what policies will be installed for the subscriber for 
  # each APN
  active_policies_by_apn: dict[string, array[string]]
  ...
```
