### ISSUE TITLE
[orc8r] Modify API for LTE gateways to specify APN resources

### ISSUE THREAD

**Issue by andreilee** [magma/magma#2256]
We'll need to modify our swagger API to add APN resource definitions for gateways
```
mutable_lte_gateway:
  id: string
  name: string
  description: string
  ...
  apn_resources: array[string]
  ...
```
