### ISSUE TITLE
NMS: Add support for header enrichment 

### ISSUE THREAD

**Issue by pshelar** [magma/magma#3620]

**Comment by pshelar** [comment]
Add support to add URLs to header enrichment policy rule.
PR that added Orc8r API: https://github.com/magma/magma/pull/3613

**Comment by karthiksubraveti** [comment]
Add work associated with following issue also in here.

NMS: Add config option to add advanced header enrichment configuration. #3691
https://github.com/magma/magma/issues/3691

This would configured using AGW pipelineD mconfig.

Encryption algorithm
Key

**Comment by karthiksubraveti** [comment]
Enables following attributes from gateway configuration page
```
  gateway_he_config:
    description: Header Enrichment configuration
    type: object
    required:
      - enable_header_enrichment
      - enable_encryption
      - he_encryption_algorithm
      - he_hash_function
      - he_encoding_type
    properties:
      enable_header_enrichment:
        description: True if header enrichment feature should be disabled for gateway
        type: boolean
        example: false
        x-nullable: false
        default: true
      enable_encryption:
        description: True if headers should be encrypted
        type: boolean
        x-nullable: false
        example: true
      encryption_key:
        description: Key to be used in header encryption
        type: string
        x-nullable: false
        example: 'C14r0315v0x'
      he_encryption_algorithm:
        type: string
        x-nullable: false
        enum:
          - 'RC4'
        example: 'RC4'
      he_hash_function:
        type: string
        x-nullable: false
        enum:
          - 'MD5'
        example: 'MD5'
      he_encoding_type:
        type: string
        x-nullable: false
        enum:
          - 'BASE64'
        example: 'BASE64'
```

**Comment by karthiksubraveti** [comment]
Add following attribute to policy configuration page 

```
      header_enrichment_targets:
        type: array
        description: List of URL targets for header enrichment
        items:
          type: string
          x-nullable: false
          example: http://example.com/
```
