### ISSUE TITLE
[Magma NMS/FeG] Mapping Service Identifier with Rating group for CCR-I to OCS

### ISSUE THREAD

**Issue by emersonacuna** [magma/magma#7498]
### Federated LTE Network

- **Version:** 1.4
- **Affected Component:** Orchestrator, Access Gateway, NMS, FeG
- **Affected Subcomponent:** Orchestrator, Access Gateway, NMS, FeG
- **Deployment Environment:** local docker-compose (orc8r), openstack AGW/FeGW

### Describe the Feature
Able to add Service Identifier mapping together to Rating Group. This is in order to include AVP code 439 Service-Identifier inside AVP MSCC in CCR-I send to OCS. 

**Specify the applicable product use-cases**
FWA telecom operator

**Describe the solution you'd like**
Able to add Service Identifier mapping together to Rating Group. This is in order to include AVP code 439 Service-Identifier inside AVP MSCC in CCR-I send to OCS. 

Similar feature has been added for CLI Gy test: https://github.com/magma/magma/pull/7014

**Comment by uri200** [comment]
Service identifier is already taken in our PCEF (sessiond) and sent by the FEG http://github.com/magma/magma/blob/master/feg/gateway/services/session_proxy/credit_control/gy/gy_client.go#L403-L403

Per our code we use service identifier and rating group to set the mapping. 

Can you describe the current issue you see with pcaps and session_proxy logs please? It would be good to enable grpc logging at session_proxy

```
  session_proxy:
    <<: *goservice
    environment:
      USE_GY_FOR_AUTH_ONLY: ${USE_GY_FOR_AUTH_ONLY}
      GY_SUPPORTED_VENDOR_IDS: ${GY_SUPPORTED_VENDOR_IDS}
      GY_SERVICE_CONTEXT_ID: ${GY_SERVICE_CONTEXT_ID}
      MAGMA_PRINT_GRPC_PAYLOAD: 1 							<----- ADD THIS FOR LOGGING GRPC
    container_name: session_proxy 
    command: envdir /var/opt/magma/envdir /var/opt/magma/bin/session_proxy -logtostderr=true -v=9
```

Note the feature added 7014 was just a CLI field, just to include a value on that AVP that the CLI didn't have before.
