### ISSUE TITLE
AGW: Dependency Graph

### ISSUE THREAD

**Issue by bmurithi** [magma/magma#7806]
### Your Environment

- **Version: 1.5.1**
- **Affected Component:** Access Gateway
- **Affected Subcomponent:** Acess Gateway
- **Deployment Environment:** ebare-metal (AGW),

### Runtime dependencies too deep in ovs_deploy/magma_deploy role

Are all these required? Particularly `python-all`

````
- name: Install runtime dependencies.
  become: yes
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - graphviz
      - python-all
      - python-twisted-conch
      - module-assistant
      - openssl
      - dkms
      - uuid-runtime

````

**Expected behavior**

Explicit depedencies should be part of debcontrol
