### ISSUE TITLE
[FeG][Gy] CCA-U with result code 5002 UNKNOWN SESSION ID and 5004 INVALID AVP VALUE after Re-Auth Process

### ISSUE THREAD

**Issue by lulloaX** [magma/magma#8663]
### Your Environment

- **Version:** 1.6
- **Affected Component:** Fed Gateway
- **Affected Subcomponent:** Fed Gateway
- **Deployment Environment:** local docker-compose (orc8r), Openstack AGW/FeG)

### Describe the Issue

FeG received a command code: 258 Re-Auth from Commercial OCS with Re-Auth Request Type AVP on 0 value (AUTHORIZE_ONLY) in Frame #125867.
![image](https://user-images.githubusercontent.com/28659806/129771890-3a8f2bf9-b0fa-4d0c-8caa-d33a697cddd1.png)
 
FeG replied it with result code 2002 DIAMETER_LIMITED_SUCCESS.
![image](https://user-images.githubusercontent.com/28659806/129772061-978cdd4f-f813-41bf-b718-25bddbcf8084.png)

After that FeG send three CCR-U (one per each MSCC) with 3GPP-Reporting-Reason AVP on 7 value (FORCED_AUTHORIZATION), but commercial OCS replied CCA-U messages with result code 5002 DIAMETER_UNKNOW_SESSION ID and 5004 DIAMETER_INVALID_AVP_VALUE, it forced an CCR-T from FeG to OCS but it also failed with result code 5002 DIAMETER_UNKNOW_SESSION_ID on CCA-T.
![image](https://user-images.githubusercontent.com/28659806/129774933-218d9882-9bf8-46c8-9bd4-1278f0e04fc7.png)

**Expected behavior**

Because of OCS is on commercial state, the same Re-Auth procedure happen everyday on commercial scenario but in this case SPGW send a CCR-U message for first MSCC and wait its CCA-U before send the second CCR-U for next MSCC.

**Additional context**

- Attach the logs for session_proxy (Line 4887) and s6a_proxy (Line 2112) services.
[fegActive_1708_logs.zip](https://github.com/magma/magma/files/7002125/fegActive_1708_logs.zip)

- Attach the pcap trace, see Frame #125867
[trace_1608_feg03_act.zip](https://github.com/magma/magma/files/7002128/trace_1608_feg03_act.zip)

**Comment by uri200** [comment]
Hey @LuisUlloaB the pcap provided doesn't have frame 125867 (RAR)

Can you please provide pcap for that?

Can you please split this into two issues (RAR and CCR-U)

**Comment by uri200** [comment]
@LuisUlloaB can you repeat the test with grpc logging enabled on feg please 
`MAGMA_PRINT_GRPC_PAYLOAD: 1`
`-v=9`

```
 session_proxy:
    <<: *goservice
    environment:
      USE_GY_FOR_AUTH_ONLY: ${USE_GY_FOR_AUTH_ONLY}
      GY_SUPPORTED_VENDOR_IDS: ${GY_SUPPORTED_VENDOR_IDS}
      GY_SERVICE_CONTEXT_ID: ${GY_SERVICE_CONTEXT_ID}
      DISABLE_REQUESTED_SERVICE_UNIT_AVP: ${DISABLE_REQUESTED_SERVICE_UNIT_AVP}
      MAGMA_PRINT_GRPC_PAYLOAD: 1             <---------
    container_name: session_proxy
    command: envdir /var/opt/magma/envdir /var/opt/magma/bin/session_proxy -logtostderr=true -v=9   <-----
```

Also can you include sessiond logs with debug and grpc enabled: on `sessiond.yml` change 
```
log_level: DEBUG
print_grpc_payload: true
```
