### ISSUE TITLE
[orc8r][kubernetes][on-premise] Error getting event counts

### ISSUE THREAD

**Issue by caprivm** [magma/magma#8903]
### Your Environment

- **Version:**
- **Affected Component:** Orchestrator, NMS
- **Affected Subcomponent:** Orchestrator pod/service
- **Deployment Environment:** Orchestrator on-premise (Kubernetes)
 
### Describe the Issue

I'm having this problem `Error getting event counts` after deploying the on-premise orchestrator. In the _Dashboard_ tab of the NMS this error appears once the UI is opened.

**To Reproduce**
1. Build and register the orchestrator containers
2. Build the Helm Packages
3. Install the Helm Packages using the default values
4. Go to the NMS, tab dashboards

**Expected behavior**
No error getting the event counts.

**Screenshots**
![image](https://user-images.githubusercontent.com/64229476/131423318-3e9fd4ed-6b16-4cdd-b17b-e893476d342c.png)

### Solution
In the values that you use to deploy the orchestrator with Helm, change the `eventd` service section for:
```yaml
eventd:
  service:
    labels:
      orc8r.io/obsidian_handlers: "true"
      orc8r.io/swagger_spec: "true"
    annotations:
      orc8r.io/obsidian_handlers_path_prefixes: >
        /magma/v1/networks/:network_id/logs,
        /magma/v1/events,
        /magma/v1/events/:network_id,
        /magma/v1/events/:network_id/about,
        /magma/v1/events/:network_id/about/count,
```
Next, upgrade your deployment and restart the `obsidian` pod:
```bash
helm -n magma upgrade --install orc8r magma-charts/orc8r --values values_orc8r.yaml
kubectl delete pod orc8r-obsidian-<id> -n magma
```

### Next steps
Although the error no longer appears, I will validate what happens with the elastic deployment that does not deliver the events to the NMS. I will update this issue when I know what it can be.
